# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1e1e40055b2552bdb28cfa3262009d89b70e7c564de51fc6bfc8171b898c7f856f4b6f22b640e3747b266921166cad32f4c06a0f4c9deb244f0f2027360d71a

test:
  secret_key_base: eae479af3786e648210a29d543d79f3344ab2ab48ebffc08d9136d6a1f316a1998c75471d34e14a7a726d8ce940fe24337073d326ebfff90157b9a622753c65d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
